# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AcctProp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AcctProp.proto',
  package='login.proto',
  serialized_pb='\n\x0e\x41\x63\x63tProp.proto\x12\x0blogin.proto\"7\n\x08\x41\x63\x63tProp\x12\x13\n\x0bproperty_id\x18\x01 \x02(\r\x12\x16\n\x0eproperty_value\x18\x02 \x02(\x05')




_ACCTPROP = _descriptor.Descriptor(
  name='AcctProp',
  full_name='login.proto.AcctProp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='property_id', full_name='login.proto.AcctProp.property_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='property_value', full_name='login.proto.AcctProp.property_value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['AcctProp'] = _ACCTPROP

class AcctProp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCTPROP

  # @@protoc_insertion_point(class_scope:login.proto.AcctProp)


# @@protoc_insertion_point(module_scope)
