# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthSessionTokenReq.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AuthSessionTokenReq.proto',
  package='login.proto',
  serialized_pb='\n\x19\x41uthSessionTokenReq.proto\x12\x0blogin.proto\",\n\x13\x41uthSessionTokenReq\x12\x15\n\rsession_token\x18\x01 \x02(\x0c')




_AUTHSESSIONTOKENREQ = _descriptor.Descriptor(
  name='AuthSessionTokenReq',
  full_name='login.proto.AuthSessionTokenReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_token', full_name='login.proto.AuthSessionTokenReq.session_token', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['AuthSessionTokenReq'] = _AUTHSESSIONTOKENREQ

class AuthSessionTokenReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHSESSIONTOKENREQ

  # @@protoc_insertion_point(class_scope:login.proto.AuthSessionTokenReq)


# @@protoc_insertion_point(module_scope)
