# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthSessionTokenReply.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ResultCodes_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AuthSessionTokenReply.proto',
  package='login.proto',
  serialized_pb='\n\x1b\x41uthSessionTokenReply.proto\x12\x0blogin.proto\x1a\x11ResultCodes.proto\"E\n\x15\x41uthSessionTokenReply\x12,\n\x0bresult_code\x18\x01 \x02(\x0e\x32\x17.login.proto.ResultCode')




_AUTHSESSIONTOKENREPLY = _descriptor.Descriptor(
  name='AuthSessionTokenReply',
  full_name='login.proto.AuthSessionTokenReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_code', full_name='login.proto.AuthSessionTokenReply.result_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=132,
)

_AUTHSESSIONTOKENREPLY.fields_by_name['result_code'].enum_type = ResultCodes_pb2._RESULTCODE
DESCRIPTOR.message_types_by_name['AuthSessionTokenReply'] = _AUTHSESSIONTOKENREPLY

class AuthSessionTokenReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHSESSIONTOKENREPLY

  # @@protoc_insertion_point(class_scope:login.proto.AuthSessionTokenReply)


# @@protoc_insertion_point(module_scope)
