# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CharSummary.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CharSummary.proto',
  package='login.proto',
  serialized_pb='\n\x11\x43harSummary.proto\x12\x0blogin.proto\"b\n\x0b\x43harSummary\x12\x11\n\tserver_id\x18\x01 \x02(\r\x12\x14\n\x0c\x63haracter_id\x18\x02 \x02(\r\x12\x18\n\x10last_played_time\x18\x03 \x02(\x03\x12\x10\n\x08xml_data\x18\x04 \x01(\t')




_CHARSUMMARY = _descriptor.Descriptor(
  name='CharSummary',
  full_name='login.proto.CharSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='login.proto.CharSummary.server_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='character_id', full_name='login.proto.CharSummary.character_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_played_time', full_name='login.proto.CharSummary.last_played_time', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xml_data', full_name='login.proto.CharSummary.xml_data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['CharSummary'] = _CHARSUMMARY

class CharSummary(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHARSUMMARY

  # @@protoc_insertion_point(class_scope:login.proto.CharSummary)


# @@protoc_insertion_point(module_scope)
