# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClusterInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ServerInfo_pb2
import ClusterProp_pb2
import ClusterStatus_pb2
import ClusterPopStatus_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClusterInfo.proto',
  package='login.proto',
  serialized_pb='\n\x11\x43lusterInfo.proto\x12\x0blogin.proto\x1a\x10ServerInfo.proto\x1a\x11\x43lusterProp.proto\x1a\x13\x43lusterStatus.proto\x1a\x16\x43lusterPopStatus.proto\"\xf0\x02\n\x0b\x43lusterInfo\x12\x12\n\ncluster_id\x18\x01 \x02(\r\x12\x14\n\x0c\x63luster_name\x18\x02 \x02(\t\x12\x12\n\nlobby_host\x18\x03 \x01(\t\x12\x12\n\nlobby_port\x18\x04 \x01(\r\x12\x13\n\x0b\x63luster_pop\x18\x05 \x01(\r\x12\x17\n\x0fmax_cluster_pop\x18\x06 \x01(\r\x12\x39\n\x12\x63luster_pop_status\x18\x07 \x01(\x0e\x32\x1d.login.proto.ClusterPopStatus\x12\x13\n\x0blanguage_id\x18\x08 \x02(\r\x12\x32\n\x0e\x63luster_status\x18\t \x02(\x0e\x32\x1a.login.proto.ClusterStatus\x12,\n\x0bserver_list\x18\n \x03(\x0b\x32\x17.login.proto.ServerInfo\x12/\n\rproperty_list\x18\x0b \x03(\x0b\x32\x18.login.proto.ClusterProp')




_CLUSTERINFO = _descriptor.Descriptor(
  name='ClusterInfo',
  full_name='login.proto.ClusterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='login.proto.ClusterInfo.cluster_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_name', full_name='login.proto.ClusterInfo.cluster_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobby_host', full_name='login.proto.ClusterInfo.lobby_host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobby_port', full_name='login.proto.ClusterInfo.lobby_port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_pop', full_name='login.proto.ClusterInfo.cluster_pop', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_cluster_pop', full_name='login.proto.ClusterInfo.max_cluster_pop', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_pop_status', full_name='login.proto.ClusterInfo.cluster_pop_status', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language_id', full_name='login.proto.ClusterInfo.language_id', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_status', full_name='login.proto.ClusterInfo.cluster_status', index=8,
      number=9, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_list', full_name='login.proto.ClusterInfo.server_list', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='property_list', full_name='login.proto.ClusterInfo.property_list', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=485,
)

_CLUSTERINFO.fields_by_name['cluster_pop_status'].enum_type = ClusterPopStatus_pb2._CLUSTERPOPSTATUS
_CLUSTERINFO.fields_by_name['cluster_status'].enum_type = ClusterStatus_pb2._CLUSTERSTATUS
_CLUSTERINFO.fields_by_name['server_list'].message_type = ServerInfo_pb2._SERVERINFO
_CLUSTERINFO.fields_by_name['property_list'].message_type = ClusterProp_pb2._CLUSTERPROP
DESCRIPTOR.message_types_by_name['ClusterInfo'] = _CLUSTERINFO

class ClusterInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLUSTERINFO

  # @@protoc_insertion_point(class_scope:login.proto.ClusterInfo)


# @@protoc_insertion_point(module_scope)
