# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClusterPopStatus.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClusterPopStatus.proto',
  package='login.proto',
  serialized_pb='\n\x16\x43lusterPopStatus.proto\x12\x0blogin.proto*Y\n\x10\x43lusterPopStatus\x12\x0f\n\x0bPOP_UNKNOWN\x10\x00\x12\x0b\n\x07POP_LOW\x10\x01\x12\x0b\n\x07POP_MED\x10\x02\x12\x0c\n\x08POP_HIGH\x10\x03\x12\x0c\n\x08POP_FULL\x10\x04')

_CLUSTERPOPSTATUS = _descriptor.EnumDescriptor(
  name='ClusterPopStatus',
  full_name='login.proto.ClusterPopStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POP_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POP_LOW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POP_MED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POP_HIGH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POP_FULL', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=39,
  serialized_end=128,
)

ClusterPopStatus = enum_type_wrapper.EnumTypeWrapper(_CLUSTERPOPSTATUS)
POP_UNKNOWN = 0
POP_LOW = 1
POP_MED = 2
POP_HIGH = 3
POP_FULL = 4




# @@protoc_insertion_point(module_scope)
