# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ResultCodes_pb2
import AcctProp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='login.proto',
  serialized_pb='\n\ntest.proto\x12\x0blogin.proto\x1a\x11ResultCodes.proto\x1a\x0e\x41\x63\x63tProp.proto\">\n\x12GetAcctPropListReq\x12(\n\tprop_list\x18\x01 \x03(\x0b\x32\x15.login.proto.AcctProp')




_GETACCTPROPLISTREQ = _descriptor.Descriptor(
  name='GetAcctPropListReq',
  full_name='login.proto.GetAcctPropListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prop_list', full_name='login.proto.GetAcctPropListReq.prop_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=124,
)

_GETACCTPROPLISTREQ.fields_by_name['prop_list'].message_type = AcctProp_pb2._ACCTPROP
DESCRIPTOR.message_types_by_name['GetAcctPropListReq'] = _GETACCTPROPLISTREQ

class GetAcctPropListReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETACCTPROPLISTREQ

  # @@protoc_insertion_point(class_scope:login.proto.GetAcctPropListReq)


# @@protoc_insertion_point(module_scope)
