# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetAcctPropListReply.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ResultCodes_pb2
import AcctProp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetAcctPropListReply.proto',
  package='login.proto',
  serialized_pb='\n\x1aGetAcctPropListReply.proto\x12\x0blogin.proto\x1a\x11ResultCodes.proto\x1a\x0e\x41\x63\x63tProp.proto\"n\n\x14GetAcctPropListReply\x12,\n\x0bresult_code\x18\x01 \x02(\x0e\x32\x17.login.proto.ResultCode\x12(\n\tprop_list\x18\x02 \x03(\x0b\x32\x15.login.proto.AcctProp')




_GETACCTPROPLISTREPLY = _descriptor.Descriptor(
  name='GetAcctPropListReply',
  full_name='login.proto.GetAcctPropListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_code', full_name='login.proto.GetAcctPropListReply.result_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prop_list', full_name='login.proto.GetAcctPropListReply.prop_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=188,
)

_GETACCTPROPLISTREPLY.fields_by_name['result_code'].enum_type = ResultCodes_pb2._RESULTCODE
_GETACCTPROPLISTREPLY.fields_by_name['prop_list'].message_type = AcctProp_pb2._ACCTPROP
DESCRIPTOR.message_types_by_name['GetAcctPropListReply'] = _GETACCTPROPLISTREPLY

class GetAcctPropListReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETACCTPROPLISTREPLY

  # @@protoc_insertion_point(class_scope:login.proto.GetAcctPropListReply)


# @@protoc_insertion_point(module_scope)
