# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetClusterListReply.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ResultCodes_pb2
import ClusterInfo_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetClusterListReply.proto',
  package='login.proto',
  serialized_pb='\n\x19GetClusterListReply.proto\x12\x0blogin.proto\x1a\x11ResultCodes.proto\x1a\x11\x43lusterInfo.proto\"s\n\x13GetClusterListReply\x12,\n\x0bresult_code\x18\x01 \x02(\x0e\x32\x17.login.proto.ResultCode\x12.\n\x0c\x63luster_list\x18\x02 \x03(\x0b\x32\x18.login.proto.ClusterInfo')




_GETCLUSTERLISTREPLY = _descriptor.Descriptor(
  name='GetClusterListReply',
  full_name='login.proto.GetClusterListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_code', full_name='login.proto.GetClusterListReply.result_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_list', full_name='login.proto.GetClusterListReply.cluster_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=195,
)

_GETCLUSTERLISTREPLY.fields_by_name['result_code'].enum_type = ResultCodes_pb2._RESULTCODE
_GETCLUSTERLISTREPLY.fields_by_name['cluster_list'].message_type = ClusterInfo_pb2._CLUSTERINFO
DESCRIPTOR.message_types_by_name['GetClusterListReply'] = _GETCLUSTERLISTREPLY

class GetClusterListReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETCLUSTERLISTREPLY

  # @@protoc_insertion_point(class_scope:login.proto.GetClusterListReply)


# @@protoc_insertion_point(module_scope)
