# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MetricEventNotify.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MetricEventNotify.proto',
  package='login.proto',
  serialized_pb='\n\x17MetricEventNotify.proto\x12\x0blogin.proto\"9\n\x11MetricEventNotify\x12\x10\n\x08\x65vent_id\x18\x01 \x02(\r\x12\x12\n\nevent_data\x18\x02 \x01(\x0c')




_METRICEVENTNOTIFY = _descriptor.Descriptor(
  name='MetricEventNotify',
  full_name='login.proto.MetricEventNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_id', full_name='login.proto.MetricEventNotify.event_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_data', full_name='login.proto.MetricEventNotify.event_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['MetricEventNotify'] = _METRICEVENTNOTIFY

class MetricEventNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METRICEVENTNOTIFY

  # @@protoc_insertion_point(class_scope:login.proto.MetricEventNotify)


# @@protoc_insertion_point(module_scope)
