# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResultCodes.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResultCodes.proto',
  package='login.proto',
  serialized_pb='\n\x11ResultCodes.proto\x12\x0blogin.proto*\xbc\x02\n\nResultCode\x12\x0f\n\x0bRES_SUCCESS\x10\x00\x12\x1c\n\x18RES_PROTOCOL_UNSUPPORTED\x10\x01\x12\x1b\n\x17RES_PRODUCT_UNSUPPORTED\x10\x02\x12\x1b\n\x17RES_ACCOUNT_AUTH_FAILED\x10\x03\x12\x1a\n\x16RES_ACCOUNT_TERMINATED\x10\x04\x12\x17\n\x13RES_ACCOUNT_EXPIRED\x10\x05\x12\x19\n\x15RES_ACCOUNT_SUSPENDED\x10\x06\x12%\n!RES_ACCOUNT_SECONDARY_AUTH_NEEDED\x10\x07\x12\x1e\n\x1aRES_ACCOUNT_ALREADY_ONLINE\x10\x08\x12\x14\n\x10RES_SYSTEM_ERROR\x10\t\x12\x18\n\x14RES_ENCRYPTION_ERROR\x10\n')

_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='login.proto.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RES_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_PROTOCOL_UNSUPPORTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_PRODUCT_UNSUPPORTED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ACCOUNT_AUTH_FAILED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ACCOUNT_TERMINATED', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ACCOUNT_EXPIRED', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ACCOUNT_SUSPENDED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ACCOUNT_SECONDARY_AUTH_NEEDED', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ACCOUNT_ALREADY_ONLINE', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_SYSTEM_ERROR', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ENCRYPTION_ERROR', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=35,
  serialized_end=351,
)

ResultCode = enum_type_wrapper.EnumTypeWrapper(_RESULTCODE)
RES_SUCCESS = 0
RES_PROTOCOL_UNSUPPORTED = 1
RES_PRODUCT_UNSUPPORTED = 2
RES_ACCOUNT_AUTH_FAILED = 3
RES_ACCOUNT_TERMINATED = 4
RES_ACCOUNT_EXPIRED = 5
RES_ACCOUNT_SUSPENDED = 6
RES_ACCOUNT_SECONDARY_AUTH_NEEDED = 7
RES_ACCOUNT_ALREADY_ONLINE = 8
RES_SYSTEM_ERROR = 9
RES_ENCRYPTION_ERROR = 10




# @@protoc_insertion_point(module_scope)
