# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServerInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServerInfo.proto',
  package='login.proto',
  serialized_pb='\n\x10ServerInfo.proto\x12\x0blogin.proto\"4\n\nServerInfo\x12\x11\n\tserver_id\x18\x01 \x02(\r\x12\x13\n\x0bserver_name\x18\x02 \x02(\t')




_SERVERINFO = _descriptor.Descriptor(
  name='ServerInfo',
  full_name='login.proto.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='login.proto.ServerInfo.server_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_name', full_name='login.proto.ServerInfo.server_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO

class ServerInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERINFO

  # @@protoc_insertion_point(class_scope:login.proto.ServerInfo)


# @@protoc_insertion_point(module_scope)
