# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VerifyProtocolReply.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ResultCodes_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VerifyProtocolReply.proto',
  package='login.proto',
  serialized_pb='\n\x19VerifyProtocolReply.proto\x12\x0blogin.proto\x1a\x11ResultCodes.proto\"]\n\x13VerifyProtocolReply\x12,\n\x0bresult_code\x18\x01 \x02(\x0e\x32\x17.login.proto.ResultCode\x12\x0b\n\x03iv1\x18\x02 \x01(\x0c\x12\x0b\n\x03iv2\x18\x03 \x01(\x0c')




_VERIFYPROTOCOLREPLY = _descriptor.Descriptor(
  name='VerifyProtocolReply',
  full_name='login.proto.VerifyProtocolReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_code', full_name='login.proto.VerifyProtocolReply.result_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iv1', full_name='login.proto.VerifyProtocolReply.iv1', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iv2', full_name='login.proto.VerifyProtocolReply.iv2', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=154,
)

_VERIFYPROTOCOLREPLY.fields_by_name['result_code'].enum_type = ResultCodes_pb2._RESULTCODE
DESCRIPTOR.message_types_by_name['VerifyProtocolReply'] = _VERIFYPROTOCOLREPLY

class VerifyProtocolReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERIFYPROTOCOLREPLY

  # @@protoc_insertion_point(class_scope:login.proto.VerifyProtocolReply)


# @@protoc_insertion_point(module_scope)
