# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VerifyProtocolReq.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VerifyProtocolReq.proto',
  package='login.proto',
  serialized_pb='\n\x17VerifyProtocolReq.proto\x12\x0blogin.proto\"\\\n\x11VerifyProtocolReq\x12\x18\n\x10protocol_version\x18\x01 \x02(\r\x12\x12\n\nproduct_id\x18\x02 \x02(\r\x12\x19\n\x11\x63lient_public_key\x18\x03 \x02(\x0c')




_VERIFYPROTOCOLREQ = _descriptor.Descriptor(
  name='VerifyProtocolReq',
  full_name='login.proto.VerifyProtocolReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='login.proto.VerifyProtocolReq.protocol_version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='login.proto.VerifyProtocolReq.product_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_public_key', full_name='login.proto.VerifyProtocolReq.client_public_key', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['VerifyProtocolReq'] = _VERIFYPROTOCOLREQ

class VerifyProtocolReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERIFYPROTOCOLREQ

  # @@protoc_insertion_point(class_scope:login.proto.VerifyProtocolReq)


# @@protoc_insertion_point(module_scope)
